### ISSUE TITLE
Error LAMA0001 when compiling in an official .net 6.0 docker image using CPM

### ISSUE THREAD

**Issue by aabs** [postsharp/Metalama#151]
I'm experiencing some issues using Metalama on a project using central package version management.  Within Visual Studio Version 17.7.0 Preview 1.0 I see no issues building and running a simple aspect.  But, when I try to build the same project within a docker container based on [mcr.microsoft.com/dotnet/sdk:6.0](http://mcr.microsoft.com/dotnet/sdk:6.0) I start seeing errors like the following:

    #44 9.163 CSC : error LAMA0001: Unexpected exception occurred in Metalama: Error calling "/usr/share/dotnet/dotnet" build -bl:msbuild_92fa161e5e7146308c5ed67a722ecc18.binlog in /tmp/Metalama/AssemblyLocator/2023.1.5-preview/default returned 1. Process output: [/src/simul8.core/simul8.core.csproj]

    #44 9.164 /tmp/Metalama/AssemblyLocator/2023.1.5-preview/default/TempProject.csproj : error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items:
I've confirmed that no projects actually have the wrong form of Nuget references/versions defined, so I can only assume that Metalama is trying to dynamically add a package at build time, without taking into account that the project uses CPM.
Is CPM even supported?

**Comment by gfraiteur** [comment]
It should be solved in 2023.1-rc. Please confirm.

**Comment by aabs** [comment]
Hi, I just checked the nuget package `2023.1.8-rc`, and the issue is still there for the docker build.

Got this on a recent build:

```
/tmp/Metalama/AssemblyLocator/2023.1.8-rc/default/TempProject.csproj : error NU1008: Projects \
that use central package version management should not define the version on the PackageReference \
items but on the PackageVersion items: Microsoft.CodeAnalysis.CSharp;System.Collections.Immutable;\
Microsoft.CodeAnalysis.CSharp;System.Collections.Immutable;Microsoft.CodeAnalysis.CSharp;\
System.Collections.Immutable. [/src/simul8.core/simul8.core.csproj]
```

Just for the record, I don't reference `System.Collections.Immutable` anywhere in this codebase, meaning it's a transitive dependency.  Not sure where from though.

The relevant RUN entry in the `Dockerfile` was as follows:

```Dockerfile
RUN dotnet new tool-manifest && \
    dotnet tool install metalama.tool && \
    dotnet metalama license free && \
    dotnet build "simul8.controlapi.csproj" -c Release -o /app/build
```

**Comment by gfraiteur** [comment]
Could you please send the `binlog` files you will find under the `/tmp/Metalama/AssemblyLocator/2023.1.8-rc/default/` directory? If you don't want to make it public, please create a private ticket on https://support.postsharp.net with a reference to this ticket.

Thanks!

**Comment by gfraiteur** [comment]
Kind reminder.

**Comment by svick** [comment]
This should be fixed in 2023.2.2-rc.
